### ISSUE TITLE
Is it possible to run scripts on an instance via the API?

### ISSUE THREAD

**Issue by varun19299** [genesiscloud/py-genesiscloud#6]
Hi,

While the API can create & manage resources, would it be possible to run a script / code on it?

**Comment by oz123** [comment]
Like with any cloud provider, yes. Use `user_data` to pass either a cloud-init config or a bash script.

**Comment by varun19299** [comment]
Slightly tangential question:

```

INSTANCE_TYPES = {
    'vcpu-4_memory-12g_disk-80g_nvidia1080ti-1':
    {"vCPUs": 4, "RAM":  12, "Disk": 80, "GPU": 1},
    'vcpu-8_memory-24g_disk-80g_nvidia1080ti-2':
    {"vCPUs": 8, "RAM":  24, "Disk": 80, "GPU": 2},
    'vcpu-12_memory-36g_disk-80g_nvidia1080ti-3':
    {"vCPUs": 12, "RAM": 36, "Disk": 80, "GPU": 3},
    'vcpu-16_memory-48g_disk-80g_nvidia1080ti-4':
    {"vCPUs": 16, "RAM": 48, "Disk": 80, "GPU": 4},
    'vcpu-20_memory-60g_disk-80g_nvidia1080ti-5':
    {"vCPUs": 20, "RAM": 60, "Disk": 80, "GPU": 5},
    'vcpu-24_memory-72g_disk-80g_nvidia1080ti-6':
    {"vCPUs": 24, "RAM": 72, "Disk": 80, "GPU": 6},
    'vcpu-28_memory-84g_disk-80g_nvidia1080ti-7':
    {"vCPUs": 28, "RAM": 84, "Disk": 80, "GPU": 7},
    'vcpu-32_memory-96g_disk-80g_nvidia1080ti-8':
    {"vCPUs": 32, "RAM": 96, "Disk": 80, "GPU": 8},
    'vcpu-36_memory-108g_disk-80g_nvidia1080ti-9':
    {"vCPUs": 36, "RAM": 108, "Disk": 80, "GPU": 9},
    'vcpu-40_memory-120g_disk-80g_nvidia1080ti-10':
    {"vCPUs": 40, "RAM": 120, "Disk": 80, "GPU": 10},
}
```

Are CPU only instances supported?

**Comment by varun19299** [comment]
Could you provide an example on how to use `user_data`?

I'm essentially trying to create the following workflow:
1. Given a GitHub repo with a train script and its instances
2. Spin up a cloud instance
3. Run the startup script
4. Run the code
5. Wait till code finishes (or crashes)
6. Dump std logs or any others
7. Kill instance

I could club 3) with 4), but would prefer not to. Is there anyway of knowing if the instance has finished a script or not?

**Comment by oz123** [comment]
CPU instances are supported. You can modify the code to add them. 
The `example.py` should be sufficient. It shows how to use user data with example script, and how to detect whether the script finished or not. Please take a look there.

**Comment by diogopms** [comment]
@varun19299, you can check all the possible instance types on our Developer API page:
https://developers.genesiscloud.com/instances

Here an example using the create instance with startup_script script:

```python
instance = client.Instances.create(
  name='<NAME>',
  hostname='<HOSTNAME>',
  ssh_keys=[SSH_KEY_ID],
  security_groups=[<SECURITY_GROUP_ID>],
  image=<IMAGE_ID>,
  type=instance_type,
  metadata={'startup_script': '#!/bin/bash\nsudo apt update && sudo apt install iperf3'}
)
```
